### ISSUE TITLE
Error in transition definition

### ISSUE THREAD

**Issue by elboletaire** [xyl0n/iris-light#42]
Running `sudo update-manager -d` I found an error on buttons.css:

```
(utopic:21509): Gtk-WARNING **: Theme parsing error: button.css:27:21: `px' is not a valid unit.
```

taking a look at `buttons.css` we can see this:

``` css
BackgroundBox .button:active {
    transition: 100px linear;
}
```

which is not valid. A transition should be defined using a time unit, like `s` or `ms`. If that "100px" is to specify a width, it should be specified as `transition: width linear` and set the `width: 100px` in the desired element.

More information: http://www.w3schools.com/css/css3_transitions.asp
